### ISSUE TITLE
你好 请问能加入L2TP拨号模式支持吗

### ISSUE THREAD

**Issue by sfpprxy** [efateva/pssx#1]

**Comment by efateva** [comment]
您好，由于我们学校不具条件我没体验过这个拨号模式，但是脚本中调用的rasdial对于参数配置好（预共享密钥等）的l2tp连接是可以支持的，建议用闪讯官方客户端拨上以后去网络共享中心把闪讯的vpn连接复制一个副本（这样就能保留参数了，按照客户端的尿性每次退出他会和普通拨号模式一样自动删除连接，拨号的时候再重建，所以复制一个省下麻烦），然后脚本中的$pppname改成这个vpn的连接名称试试
