### ISSUE TITLE
4.15号闪讯更新后radius再次更改，请帮忙重新更新下

### ISSUE THREAD

**Issue by fengjch127** [efateva/pssx#3]
"zjxinlisx01"改成"singlenet01"也继续691
请大神更新下，
或者如果能教下这个是如何抓取到的就更完美了

**Comment by efateva** [comment]
不好意思很久没关注了，刚看了下应该没变，windows版还要脱壳比较麻烦，建议用Hopper Disassembler反编译mac版的,搜索methImpl_SNPPPoEDialController_CalcPin_

**Comment by fengjch127** [comment]
嗯，确实没变，不过应该是开了心跳检测了，估计这个用powershell脚本不容易解决吧
